bankproject/account/urls.py
from django.urls import path

from  . import views
app_name='account'

urlpatterns = [
    path('register/',views.register,name='register'),
     path('login/',views.login,name='login'),
    # path('new/',views.new,name='new'),
]

bankproject/bankapp/urls.py
from django.urls import path

from  . import views
app_name='bankapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('new/',views.new,name='new'),
    path('form/',views.form,name='form'),
    path('logout/',views.logout,name='logout'),
    path('appl/',views.appl,name='appl')
]

bankproject/bankproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bankproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("bankapp.urls")),
    path('account/',include("account.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankproject/account/models.py
from django.db import models

# Create your models here.

bankproject/bankapp/models.py
from django.db import models

# Create your models here.

bankproject/account/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.shortcuts import render,redirect

# Create your views here.
def register(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        password1=request.POST.get('confrim password')
        user=User.objects.create_user(username=username,password=password)
        user.save();
        return redirect('/')
    return render(request,'register.html')

def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        userauth=auth.authenticate(username=username,password=password)

        if userauth is not None:
            auth.login(request,userauth)
            return redirect('/')
        else:
            messages.info(request,"invalid")
            return  redirect('/login/')
    return render(request,"login.html")

bankproject/bankapp/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def index(request):
    return render(request,"index.html")
def register(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        password1=request.POST.get('confrim password')
        user=User.objects.create_user(username=username,password=password)
        user.save();
        return redirect('/login')
    return render(request,'register.html')

def login(request):
    if request.method=='POST':
        username1=request.POST['username']
        password=request.POST['password']
        userauth=auth.authenticate(username=username1,password=password)

        if userauth is not None:
            auth.login(request,userauth)
            return redirect('/new')
        else:
            messages.info(request,"invalid")
            return  redirect('/login')
    return render(request,"login.html")

def new(request):
    return render(request,"new.html")

def form(request):
    if request.method=='POST':
        return redirect('/appl')

    return render(request,"form.html")

def logout(request):
    auth.logout(request)
    return redirect('/')
def appl(request):
    return render(request,"appl.html")

bankproject/templates/appl.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>subn</title>
    <style>
        body{background-color:lavenderblush;}
    </style>
</head>
<body>
<p>Application successfully accepted.</p>
    <a href="{% url 'bankapp:index' %}">go back</a>
</body>
</html>

bankproject/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forms</title>
    <style>
        form{width:100%;height:100%;font-size:16px;background-color:paleturquoise;
        margin-right:8px;padding:20px;box-sizing:border-box;
        border-radius:10px;}
        label{width:100px; display:inline-block;}
     header{width:100%;background-color:darkmagenta;font-size:40px;color:black;margin-right:8px;}
</style>

</head>
<body>
<header > <center>APPLICATION FORM</center></header>
<form  action="" method="post"><CENTER>
   {% csrf_token %}
    <label>FirstName</label>
    <input type="text" name="name"><br>
    <label>Lastname</label>
    <input type="text" name="lastname"><br>
     <label>Date of Birth</label>
    <input type="date" name="dob"><br>
    <label>Age</label>
    <input type="number" name="age"><br>
    <label>Gender</label>
    <input type="radio" name="gender" value="male">Male
    <input type="radio" name="gender" value="female">Female<br>
    <label>Phone Number</label>
    <input type="number" name="phonenumber"><br>
    <label>EMail.Id</label>
    <input type="email" name="email"><br>
    <label>Address</label>
    <textarea rows="2" cols="20"></textarea><br>
    <label>District</label>
    <select name="district">
      <option value="palakkad">Palakkad</option>
      <option value="Thrissur">Thrissur</option>
      <option value="Kollam">Kollam</option>
      <option value="Kottayam">Kottayam</option>
      <option value="idukki">Idukki</option>
      <option value="wayanad">Wayanad</option>
      <option value="Thiruvanathapuram">Thiruvanathapuram</option>
      <option value="kozhikode">Kozhikode</option>
      <option value="kannur">Kannur</option>
      <option value="kasargode">Kasargode</option>
      <option value="malappuram">Malapuram</option>
  </select><br>
    <label>Branch</label>
    <select name="branch">
          <option value="b">_select_</option>
        <option value="palakkad">Palakkad</option>
      <option value="ernakulam">Ernakulam</option>
      <option value="Madurai">Madurai</option>
      <option value="chennai">Chennai</option>
      <option value="Kottayam">Kottayam</option>
    </select><br>
    <label>Account Type</label>
    <select name="account type">
          <option value="c">_select_</option>
        <option value="savings">Savings account</option>
      <option value="current">Current account</option>

    </select><br>
<label >Materials Provide</label>
    <input type="checkbox" name="Debit card">Debit Card
      <input type="checkbox" name="Credit card" >Credit card
      <input type="checkbox" name="cheque" >Cheque book<br>
    <input type="submit">
    <a href="{% url 'bankapp:logout' %}"><button type="button" >LOGOUT</button></a>
    </CENTER>
</form>
</body>
</html>

bankproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <style>
        h1{padding:10px;}
        form{background-color:pink;padding:20px;box-sizing:border-box;border-size:5px;}
    </style>
</head>
<body>
<form  method="post"><center>
    {% csrf_token %}
    <h1 ><center>LOGIN</center></h1>
    <input type="text" name="username" placeholder="enter your name"><br>
    <input type="password" name="password" placeholder="enter your password"><br>
    <input type="submit"><br>
    <a href="{% url 'bankapp:register' %}">Register here</a>

</center>
</form>
</body>
</html>

bankproject/templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New</title>
    <style>
     body{   background-color:lemonchiffon;}
    </style>
</head>
<body>
<p>Complete the required details..</p>
<a href="{% url 'bankapp:form' %}"><button type="button" >ClickHere</button></a>
</body>
</html>

bankproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <style>
   body{background-color:moccasin;}
    </style>
</head>
<body>
<center><h1>REGISTRATION FORM</h1></center>

<form   method="post"><center>
    {% csrf_token %}

    <input type="text" name="username" placeholder="enter your name"><br>

    <input type="password" name="password" placeholder="enter your password"><br>

    <input type="password" name="confirm password" placeholder="enter your password again"><br>

    <input type="submit"><br>
    </center>
</form>
<!--{% for msg in messages %}-->
<!--{{msg}}-->
<!--{% endfor %}-->


</body>
</html>